name: Release Minor

on:
  workflow_dispatch:
      
jobs:
  minor:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Generate next version
      uses: mathieudutour/github-tag-action@v6.0
      id: tag_version
      with:
        default_bump: minor
        release_branches: develop
        dry_run: true
        github_token: ${{ secrets.PAT }}
        
    - name: Change build.gradle version
      run: sed -i "s/^version = \"[0-9]*\.[0-9]*\.[0-9]*\"/version = \"${{ steps.tag_version.outputs.new_version }}\"/g" ./bandyer-android-design/build.gradle
   
    - name: Create Release PR
      uses: peter-evans/create-pull-request@v3
      with:
          token: ${{ secrets.PAT }}
          commit-message: Release minor version 
          title: Release v${{ steps.tag_version.outputs.new_version }}
          body: |
           This PR is Auto-generated
          branch: release-v${{ steps.tag_version.outputs.new_version }}
    
    - name: Create a GitHub release notes
      uses: ncipollo/release-action@v1
      with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          commit: release-v${{ steps.tag_version.outputs.new_version }}
    outputs:
        lversion: ${{ steps.tag_version.outputs.new_version  }}
  
  check:
    needs: minor
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Wait for build to succeed
      uses: lewagon/wait-on-check-action@v1.0.0
      with:
          ref: release-v${{ needs.minor.outputs.lversion }}
          check-name: build
          repo-token: ${{ secrets.PAT }}
          wait-interval: 20
          allowed-conclusions: success
  
  publish:
    needs: check
    name: Publish
    uses: Bandyer/Bandyer-Android-Design/.github/workflows/publish.yml@develop
  
  automerge:
    name: Merge into develop
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: merge
        uses: mtanzi/action-automerge@v1
        id: merge
        with:
          github_token: ${{ secrets.PAT }}
          source: release-v${{ needs.minor.outputs.lversion }}
          target: 'develop'
