name: Release Patch

on:
  workflow_dispatch:
      
jobs:
  patch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Generate next version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        release_branches: develop
        dry_run: true
        github_token: ${{ secrets.PAT }}
    
    - name: Change build.gradle version
      run: sed -i "s/^version = \"[0-9]*\.[0-9]*\.[0-9]*\"/version = \"${{ steps.tag_version.outputs.new_version }}\"/g" ./bandyer-android-design/build.gradle
   
    - name: Create a GitHub release
      uses: peter-evans/create-pull-request@v3
      with:
          token: ${{ secrets.PAT }}
          commit-message: Increment version ${{ steps.tag_version.outputs.new_tag }}
          title: Release ${{ steps.tag_version.outputs.new_tag }}
          body: |
           This PR is Auto-generated
          branch: release-${{ steps.tag_version.outputs.new_tag }}
    
    - name: Tag version on PR branch
      uses: mathieudutour/github-tag-action@v6.0
      with:
        release_branches: release-${{ steps.tag_version.outputs.new_tag }}
        github_token: ${{ secrets.PAT }}
