name: Publish Maven

on:
  workflow_call:
    inputs:
      release_version:
          required: true
          type: string
    secrets:
      MAVEN_ACCESSKEY:
        required: true
      MAVEN_SECRETKEY:
        required: true
      MAVEN_DISTRIBUTIONID:
        required: true
  workflow_dispatch:
      
jobs:
    publish:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
        with:
          ref: release-v${{ inputs.release_version }}
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Install boto3
        run: pip install boto3
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Set dryRun to false
        run: sed -i '/def dryRun = true/c\\tdef dryRun = false' ./publish.gradle
      - name: Update Maven credentials
        env:
          MAVEN_ACCESSKEY: ${{ secrets.MAVEN_ACCESSKEY }}
          MAVEN_SECRETKEY: ${{ secrets.MAVEN_SECRETKEY }}
          MAVEN_DISTRIBUTIONID: ${{ secrets.MAVEN_DISTRIBUTIONID }}
        run: 
            echo -e "maven.accessKey=$MAVEN_ACCESSKEY\nmaven.secretKey=$MAVEN_SECRETKEY\nmaven.distributionId=$MAVEN_DISTRIBUTIONID" >> ./local.properties
      - name: Build with Gradle
        run: ./gradlew clean assembleRelease publishUpload
